### ISSUE TITLE
Support for ES256 algorithm?

### ISSUE THREAD

**Issue by roddyyaga** [ulrikstrid/reason-jose#27]
Have you looked into using ECDSA for signatures at all?

**Comment by ulrikstrid** [comment]
I have looked into it and decided that I'll wait for support in mirage-crypto or something equivalent.
I think @hannesm has worked on EC for nocrypto at some point but I don't have an idea about how far off he is.

**Comment by roddyyaga** [comment]
Cool, thanks!
