### ISSUE TITLE
Are "use" or "alg" strictly required?

### ISSUE THREAD

**Issue by Lupus** [ulrikstrid/reason-jose#40]
The following JWK key, produced from Golang code, is rejected by the library with missing algorithm or use error:

```
{
  "e": "AQAB",
  "kid": "2aff6e30eb11dc76a38ed5d0c1d50fe8d347ffa0cc654edc4a15803f7ae3a784",
  "kty": "RSA",
  "n": "rUSAReHBQZQlb_bvTm8gkhKZhNpOyrTa0VAke2aDoNtDxImGB2cUNXxNDOJDNwzTmcuHCRe5Kx8aTx7crA1j87n6Jt9ygR5pPk_vRPk5uIbXXhVqrrSKAo9lsSGK0s2U8f2eSGVz8xg8UynLBJUJkZ-bs3sMShQW8sq7agbaWyJbZf1l_7BjNmcI_jaXuZh1AtjwvnfOOB8jZYMdZSB3RcVnvkP44KJNtsv1jwCp1nSgMwqFXHmpJTTqxlQf42dGBWbr0MfFQeTNriVPXdGnNReBIy2-1ycNLegvZ3KHE8_lMw9s2woDu1ohe0ims9WuhwBga-WnRdaROAsD3QV66w"
}
```

Quickly looking through the RFC both are considered optional, or I'm missing something?

**Comment by anmonteiro** [comment]
I think we should follow the spec closely where possible, and try to follow the old maxim of being liberal in what we accept and conservative in what we emit.
