### ISSUE TITLE
Interest in supporting ES* algorithm

### ISSUE THREAD

**Issue by dangdennis** [ulrikstrid/reason-jose#53]
Hi @ulrikstrid , do you have pointers on how I can implement support for handling ES256/ES516 signed JWTs? 

My use case involves fetching a JWKS to verify the ES256 signed jwt.

If I understand correctly, the first step likely requires picking an existing ocaml library that handles ecsda signatures. And the second would be to convert a jwks to its pem form for use (or alternatively API wise, it’ll handle the jwks).

**Comment by anmonteiro** [comment]
I believe this is already implemented, but we're not exposing the functions in the `.mli`.

**Comment by dangdennis** [comment]
So it is. My mistake! The first file I looked at, I had taken out of context cuz that was for [JWE](https://github.com/ulrikstrid/reason-jose/blob/a8e43812bc37b40cc14d3332430396902f5e91dc/jose/Jwe.ml#L106) .

**Comment by dangdennis** [comment]
It all worked nicely. Took a short time to parse your docs and tests to understand the methods I needed to complete my work.

Starting from a JSON jwks and a string jwt, I needed to 
1. `Jose.Jwks.of_string` to parse my jwks
2. `Jose.Jwt.of_string` to parse my jwt
3. Access the `kid` value in my jwt's header as `<jwt var>.header.kid`.
4. `Jose.Jwks.find_key` to grab the correct key from my jwks
5. `Jose.Jwt.validate ~jwk:key j` to finally validate.

**Comment by dangdennis** [comment]
Apologies if it came off rude. I did not intend to say it. That’s for personal documentation and as a possible reference point for future documentation work.

in the meantime, no suggestions for change.

**Comment by anmonteiro** [comment]
I just meant whether you have suggestions for a better interface. 5 steps seems a bit much for what you were trying to achieve.

**Comment by dangdennis** [comment]
With this particular use case, I’ve seen few libraries help anymore. With the primitives provided, I’d eventually create a convenience helper like so:

Jwt.validate jwks:yojson jwt:yojson => Jwt.t errors result

this would return a series of errors related to
1. Do algs match in jwks and jwt header
2. Do jwt’s header kid exist in one of the jwk
3. The other typical jwt validation errors

Maybe it’s more Ocaml like to deal with all the opaque types, but the case for going from straight json to result is quickest.

There’s also a need to create a jwks fetcher from the openid wellknown apis. Unsure if we’d want to include in this library. Ex: https://github.com/nearform/get-jwks#readme

**Comment by ulrikstrid** [comment]
There is a (`oidc`)[https://GitHub.com/ulrikstrid/ocaml-oidc] library that helps with some of the complexity you're seeing.

Jose had been built as the low level primitives. But we do want to add a higher level interface for the most common things.
