### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AndreyErmilov** [ulrikstrid/reason-jose#54]
Hi! Thank you for your work on the library 👍
Could you make please a new release to be able to use the thumbprint for ECC P-256?

**Comment by ulrikstrid** [comment]
Hello! I put it in my todo so will hopefully get to it today :+1:

**Comment by AndreyErmilov** [comment]
Hey @ulrikstrid, 
Happy New Year! :)
I believe you must be super busy now, yet I am just following you to check if you got a chance to release new version.

**Comment by ulrikstrid** [comment]
Sorry about the delay @AndreyErmilov, the release PR is here: https://github.com/ocaml/opam-repository/pull/22848

**Comment by ulrikstrid** [comment]
That was a dud, opened up https://github.com/ocaml/opam-repository/pull/22849

**Comment by AndreyErmilov** [comment]
@ulrikstrid Thank you!
